### ISSUE TITLE
Home button not responding when pressed

### ISSUE THREAD

**Issue by scottb82** [rpetrich/libactivator#108]
I am having an intermittent issue when pressing my home button either once or double pressing to get the multitasking up.

The initial press doesn't respond and go to press again and the multitasking area appears. This happens intermittently but becoming frequent.  I notice this occurring in most applications but more so in Cydia.  Not sure if this is because mobilesubstrate doesn't work 100% within Cydia eg. SBSettings, biteSMS QR and even Activator (double tap status bar to get Spotlight & doesn't work).

iPhone 4, iOS 4.1

**Comment by rpetrich** [comment]
Can you list all of the MobileSubstrate extensions you have installed?

**Comment by scottb82** [comment]
Mobile Substrate 0.9.3228-1

**Comment by scottb82** [comment]
Wasn't sure how to get the correct information but I got the below from with SBSettings  --> More --> Mobile Substrate Addons:

ActionMenu, Activator, Backgrounder, ClockHide, CylayTool, DimDelay, DisplayRecorder, FiveIconDock, FullScreenSafari, IconSupport, Infinifolders, LibWeather, LiveClock, My3G, MavigateFromMaps, PreferenceLoader, STEKiller, WeatherIconStatus, WinterBoard, _SnapTap, _SnappyHook, biteSBarClient, biteSMSsb, fis, iAnnounce, libhide, libstatusbar, notifier, preventsleep, shrink.

**Comment by PrabhuDeva** [comment]
I think I am experiencing something similar. For at least several weeks now, sometimes pressing the home button doesn't really work as it should (not sure, maybe aroung 5-10% of the times I press the home button). Sometimes the press doesn't seem to be registeres by the iPhone at all, sometimes it seems to be registered as a double press. I'm not sure what the reason for this behavior might be. Theoretically, it could be a hardware issue of the phone (defective contact of the home button?), but this issue here reminded me of my observations, so just maybe it might be related to Activator? I'm not sure, and I haven't had the time to test it for, say, several days without Activator or even without a jailbreak at all.

But a related question of mine: When looking for a quick remedy for this problem, I thought of assigning the "simulate home button" action or the new "do nothing" action to the "home button double press" gesture (I'm using one of the slide-in from bottom gestures to activate the Task Switcher, so I don't need the home button double press at all). However, this does not work. It seems that for some home button or sleep button gestures you don't allow the "do nothing" or the "simulate home/sleep button press" actions. Why is that the case? I understand that messing with the home button might be dangerous (e.g. people getting stuck in apps not being able to quit them via home button), but assigning "do nothing" or "simulate home button press" to "home button double press" doesn't seem to be dangerous to me at all, at least if you have the slightest idea of what you're doing. Could this maybe be changed to allow assigning the gesture-action combinations described above?

**Comment by rpetrich** [comment]
Assigning the home button to "do nothing" would eat the home button event, which is not what you want at all. Similarly, assigning home button press to generate home button event would create an infinite loop of home button events.

To help resolve home buttons events going missing, Activator will log which action is eating the event in the system log.
