### ISSUE TITLE
Request: Ability to sequence events

### ISSUE THREAD

**Issue by cj81499** [rpetrich/libactivator#178]
For example, every time I lock my phone, toggle wifi off **and then back on** (My wifi is weird and tends to work better when I reconnect frequently.)

**Comment by pinuke** [comment]
you can do this to an extent with v1.9.8. you can attach the listener `Switches (Deactivate): wifi` then add `Switches (Activate): wifi` that should work. If it doesn't, try to be sure there is a pause (1 sec I recommend) between each action (there probably will have to be by default, since they are part of the same action)
