### ISSUE TITLE
1.3~rc1 major issues

### ISSUE THREAD

**Issue by brannanholland** [rpetrich/libactivator#24]
Applications hang at open and never open
Crashes when trying to use any activator methods
(Unfortunately it will not go to safe mode, and it will not let me disable or uninstall activator)

**Comment by rpetrich** [comment]
Thanks for reporting this. I missed a few files when creating the RC1 deb package, and have uploaded an RC2 as replacement

**Comment by Manksgloob** [comment]
Oh boy, yes.
Something changed between the previous version and 1.3-rc1. I get hanging applications (cydia, settings) and hanging when invoking sbsettings (v 3.0.6b1) or proswitcher. Haven't tried much else since phone keeps freezing. Unlike brannanholland, I am able to reach Safe Mode though.

Had no crashes with the previous version, even with sbsettings 3.0.6b1 installed.

**Comment by Manksgloob** [comment]
D'oh, posted too late.

Great to see such a quick response though.
Thanks Ryan!

**Comment by brannanholland** [comment]
It looks like im going to have to restore. For some reason my phone skips safe mode and just respings back to normal. Im hoping i left ssh on i might be able to update it via ssh

**Comment by brannanholland** [comment]
Really messed something up this time. It wont even boot. haha. Restore here i come!

**Comment by brannanholland** [comment]
Im done with beta software. Some where along the line my bootrom got updated to 05.12.01. Looks like im going to be rocking a stock iPhone for the time being. I tried to downgrade but i had no service.

**Comment by rpetrich** [comment]
That's unfortunate. If you have SSH enabled you should be able to use tcp relay to get to it before the iPhone boots fully
