### ISSUE TITLE
Closing Music Controls with home button

### ISSUE THREAD

**Issue by Neblinio** [rpetrich/libactivator#47]
I just found a possible bug (or limitation) in Activator. If I open Music Controls popup within an app and then close the dialog with Home Button, the popup closes, but so does the app.

This is how I reproduce it.

Set Activator to open Music Controls with a Home Button double press (At Home Screen and In Application)
Open an application.
Perform a double press to open music controls.
Single click Home Button to close Music Controls.
Music Controls will close, but also the app closes.

Also, when I open Music Controls and then double press Home Button again, I get the default OS behaviour (it opens Music app, in my case)

My device:
iPod 2G (old MB model)
Firmware 3.1.3
Activator 1.3.1

**Comment by PrabhuDeva** [comment]
I'd say this is stock behavior since the iPod controls popup is a standard Apple app (even if your chosen method of activating it via Activator is not Apple standard), and in the Apple (i.e. non-jailbroken) world, pressing the home button always closes everything and brings you back to the homescreen.

**Comment by rpetrich** [comment]
Yes, I'd say this is standard behaviour. I think it's a good idea if someone writes a "home kills alerts" extension though.
