### ISSUE TITLE
[Req] Option: Disable slide in from screen button while in fullscreen

### ISSUE THREAD

**Issue by XeNoW** [rpetrich/libactivator#59]
[Req] Option: Disable Slide in from button while in fullscreen

I think it would be nice to have an option to enable/disable the Slide in gestures if you are in fullscreen. It's really annoying if you play e.g. Fruit Ninja and Kirikae (slide in from screen button) opens up =) I really like these gestures but there should be some way to control them.

Possibilities: An option to enable/disable while in fullscreen, a blacklist for certain apps or even a way to enable/disable these gestures using an other methode. (Would use Volume Display Tap for this =) )

Thanks m8 and keep up the good work ;)

**Comment by rpetrich** [comment]
Blacklist is way too complicated.

There's no foolproof way to detect "fullscreen" applications because all applications are full screen. The closest would be to detect when the statusbar is showing and assume when it isn't, slide gestures should be disabled.

I will think about it, but magic 8 ball reads... "outlook is bleak"

**Comment by rpetrich** [comment]
Meh, got bored and implemented blacklisting in 1.5.9beta1
