### ISSUE TITLE
Lockscreen iPod controls missing iPod button

### ISSUE THREAD

**Issue by jonathanjames30** [rpetrich/libactivator#61]
If iPod controls option was set for the lockscreen (i have mine set to Swipe from Bottom Left) the iPod button is missing. The only available options is the Volume slider, Next & Previous Song, Pause, and Close. 

This is my first issue logged so if i am making a mistake please do let me know :)
Thanks!

**Comment by rpetrich** [comment]
Noted. A fix has been committed for the upcoming 1.4 RC2

**Comment by PrabhuDeva** [comment]
Ryan, did you intentionally remove the iPod button on the iPod controls popup on the lockscreen? Since some time ago in another thread you said you were thinking of removing the iPod button due to possible security violations if a passcode for unlocking is set. Here, you say you'd fix it. And in the latest 1.4.0 update of today, it's still mising on the lockscreen. So what's your plan regarding this?

Anyway, I generally hope you keep the iPod controls popup selectable via Activator. I don't really like he new iPod controls in the Apple task switcher.

**Comment by rpetrich** [comment]
Right, this is intentional. Unlock, and the iPod button should be visible.

**Comment by jonathanjames30** [comment]
Yes i do admit that you are looking at things from a security angle and thats really responsible from a dev. I do see the ipod controls after i slide to unlock, but the point of having it on the homescreen is so that i get fastest way to my ipod by hitting the ipod button. 

If it is left as it is now, i will have to bring the controls up OR slide to unlock, the bring the controls up and press the ipod. But then again it questions, if i unlock it, i could just press the ipod controls.

Is there a way to implement, that if there is a passcode set then the ipod button will not work. If there isn't then the button will be visible. Or is that unrealistic. Im sorry but im not a developer so i don't understand any form of coding. 

Full respect!
Keep up the great work.
