### ISSUE TITLE
[BUG] Lockscreen + Slide in from screen bottom

### ISSUE THREAD

**Issue by XeNoW** [rpetrich/libactivator#94]
Sometimes "Slide in from screen bottom" (left/right) stops working on lockscreen.

**Comment by rpetrich** [comment]
Took me awhile to track this one down: slide gestures are captured using a transparent window along the bottom of the display that is created/destroyed when the lock/springboard/applications status changes. On 4.0, I wasn't tracking the unlock/lock notifications so the visibility of those bottom windows weren't getting updated. Fixed in the next release :)
